### ISSUE TITLE
Video's are too small after being embedded in dashboard

### ISSUE THREAD

**Issue by LogoLogics2** [sdsweb/easy-support-videos#4]
Hi,

For now I only am trying the free version, but when I enter a video url, the video that is showing in the list is very small. I tried this months ago and that time the video's where larger.

Is this a bug? The plugin has not been updated for 8 months, will it still get updates please?

**Comment by scottsousa** [comment]
@LogoLogics2 This was fixed in https://github.com/sdsweb/easy-support-videos/pull/5. Thanks for reporting the issue.
